"""
warehouse_agent.py - Goal-based agent for the warehouse navigation problem.

Lab: Artificial Intelligence Agents, Task 3.
The agent knows its state (grid position), its goal (the G square) and its
actions (Up, Down, Left, Right). It plans a collision-free path with
breadth-first search (BFS) and then executes the plan.

Run:  python3 src/warehouse_agent.py
Code generated by an LLM (Claude) from my specification, then checked by me
with the tests in tests/test_agent.py (see prompts.md and REPORT.md).
"""

from collections import deque

# ---------------------------------------------------------------------------
# 1. The environment: maps and actions
# ---------------------------------------------------------------------------

# The warehouse map from the lab sheet. '#' obstacle, '.' free, S start, G goal.
WAREHOUSE_MAP = [
    "#####################",
    "#S....#............G#",
    "#.##....##########..#",
    "#....##.............#",
    "#.######.###.#.###..#",
    "#........#..........#",
    "#####################",
]

# Same warehouse, but the goal is walled in, so no path can exist.
BLOCKED_MAP = [
    "#####################",
    "#S....#...........#G#",
    "#.##....##########.##",
    "#....##.............#",
    "#.######.###.#.###..#",
    "#........#..........#",
    "#####################",
]

# The four moves as (row change, column change). The ORDER of this list is the
# tie-break rule: when two shortest paths exist, BFS finds the one that tries
# Up before Down before Left before Right.
ACTIONS = [
    ("Up", (-1, 0)),
    ("Down", (1, 0)),
    ("Left", (0, -1)),
    ("Right", (0, 1)),
]


def parse_map(lines):
    """Turn a list of strings into (grid, start, goal) and validate it.

    Raises ValueError if the map is empty, ragged, has an unknown character,
    or does not contain exactly one S and exactly one G.
    """
    if not lines:
        raise ValueError("map is empty")
    width = len(lines[0])
    start = goal = None
    n_start = n_goal = 0
    for r, row in enumerate(lines):
        if len(row) != width:
            raise ValueError("map rows have different lengths")
        for c, ch in enumerate(row):
            if ch not in "#.SG":
                raise ValueError("unknown map character %r" % ch)
            if ch == "S":
                start, n_start = (r, c), n_start + 1
            elif ch == "G":
                goal, n_goal = (r, c), n_goal + 1
    if n_start != 1 or n_goal != 1:
        raise ValueError("map needs exactly one S and one G")
    return list(lines), start, goal


# ---------------------------------------------------------------------------
# 2. The agent: state, goal, actions and the decision-making component
# ---------------------------------------------------------------------------

class GoalBasedAgent:
    """A goal-based agent that plans with BFS and then acts on its plan."""

    def __init__(self, map_lines):
        self.grid, self.start, self.goal = parse_map(map_lines)
        self.state = self.start      # what the agent keeps: its current position
        self.nodes_expanded = 0      # statistics from the last call to plan()
        self.max_frontier = 0

    def goal_test(self, state):
        """True when the given position is the goal square."""
        return state == self.goal

    def successors(self, state):
        """Return [(action name, next position)] for every legal move."""
        result = []
        rows, cols = len(self.grid), len(self.grid[0])
        for name, (dr, dc) in ACTIONS:
            r, c = state[0] + dr, state[1] + dc
            inside = 0 <= r < rows and 0 <= c < cols   # stay on the map
            if inside and self.grid[r][c] != "#":      # never enter an obstacle
                result.append((name, (r, c)))
        return result

    def plan(self):
        """Breadth-first search from the current state to the goal.

        Returns a list of action names ([] if already at the goal) or None
        if the goal cannot be reached.
        """
        self.nodes_expanded = 0
        self.max_frontier = 0
        frontier = deque([self.state])            # FIFO queue => shortest path first
        came_from = {self.state: None}            # also serves as the visited set
        while frontier:
            self.max_frontier = max(self.max_frontier, len(frontier))
            state = frontier.popleft()
            self.nodes_expanded += 1
            if self.goal_test(state):
                return self._reconstruct(came_from, state)
            for action, nxt in self.successors(state):
                if nxt not in came_from:          # never revisit => no loops
                    came_from[nxt] = (state, action)
                    frontier.append(nxt)
        return None                               # frontier empty: goal unreachable

    @staticmethod
    def _reconstruct(came_from, state):
        """Walk back through came_from to rebuild the list of actions."""
        actions = []
        while came_from[state] is not None:
            state, action = came_from[state]
            actions.append(action)
        actions.reverse()
        return actions

    def execute(self, plan):
        """Carry out a plan one move at a time. Returns the positions visited.

        Raises ValueError if a move in the plan is not legal (i.e. a collision).
        """
        trail = [self.state]
        for action in plan:
            legal = dict(self.successors(self.state))
            if action not in legal:
                raise ValueError("illegal move %s from %s" % (action, self.state))
            self.state = legal[action]
            trail.append(self.state)
        return trail


def draw_path(grid, trail):
    """Return the map as a list of strings with '*' on the path squares."""
    rows = [list(row) for row in grid]
    for r, c in trail:
        if rows[r][c] == ".":          # keep S and G visible
            rows[r][c] = "*"
    return ["".join(row) for row in rows]


# ---------------------------------------------------------------------------
# 3. Main program
# ---------------------------------------------------------------------------

def main():
    """Solve the lab map, then demonstrate the 'no path' message."""
    print("=== 1. Environment ===")
    agent = GoalBasedAgent(WAREHOUSE_MAP)
    print("Map: %d rows x %d columns" % (len(agent.grid), len(agent.grid[0])))
    print("Start (row, col):", agent.start, " Goal (row, col):", agent.goal)
    print("\n".join(agent.grid))

    print("\n=== 2. Search algorithm ===")
    print("Breadth-first search (BFS). Every move costs one square, so BFS")
    print("returns a path with the fewest moves, and its visited set stops loops.")

    print("\n=== 3. Result on the lab map ===")
    plan = agent.plan()
    if plan is None:
        print("No path exists from S to G.")
    else:
        trail = agent.execute(plan)
        print("Plan (%d moves): %s" % (len(plan), " ".join(plan)))
        print("Path as (row, col):", trail)
        print("\n".join(draw_path(agent.grid, trail)))
        print("Agent finished at", agent.state, "- goal reached:",
              agent.goal_test(agent.state))
    print("Nodes expanded:", agent.nodes_expanded,
          " Largest frontier:", agent.max_frontier)

    print("\n=== 4. Goal walled in (no path) ===")
    blocked = GoalBasedAgent(BLOCKED_MAP)
    print("\n".join(blocked.grid))
    if blocked.plan() is None:
        print("No path exists from S to G.")
    print("Nodes expanded before giving up:", blocked.nodes_expanded)


if __name__ == "__main__":
    main()
